# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(max_length=255)),
                ('cm', models.PositiveSmallIntegerField(default=0)),
                ('td', models.PositiveSmallIntegerField(default=0)),
                ('tp', models.PositiveSmallIntegerField(default=0)),
                ('credits', models.PositiveSmallIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='module_app.module')),
            ],
            options={
                'db_table': 'courses',
                'unique_together': {('module', 'course_name')},
            },
        ),
    ]
