# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("module_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "course_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cm", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("td", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("tp", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="courses",
                        to="module_app.module",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
            },
        ),
    ]
