# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeComplaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_grade', models.FloatField()),
                ('complaint_reason', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('assigned', 'Attribuée'), ('in_review', 'En Révision'), ('resolved', 'Résolue'), ('rejected', 'Rejetée')], default='submitted', max_length=20)),
                ('new_grade', models.FloatField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grade_complaints',
            },
        ),
        migrations.CreateModel(
            name='JuryDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('admitted', 'Admis'), ('deferred', 'Ajourné'), ('repeat', 'Redoublement'), ('excluded', 'Exclu')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jury_decisions',
            },
        ),
        migrations.CreateModel(
            name='JurySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=255)),
                ('session_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('in_progress', 'En Cours'), ('completed', 'Terminé')], default='scheduled', max_length=20)),
                ('minutes_document', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'jury_sessions',
            },
        ),
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('transcript', 'Relevé de Notes'), ('certificate', 'Certificat'), ('minutes', 'Procès-Verbal'), ('circular', 'Circulaire'), ('service_note', 'Note de Service')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_signature', 'En Attente de Signature'), ('signed', 'Signé'), ('archived', 'Archivé')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'official_documents',
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_taught', models.IntegerField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('submitted', 'Soumise'), ('verified', 'Vérifiée'), ('approved', 'Approuvée'), ('signed', 'Signée'), ('sent_to_finance', 'Envoyée aux Finances'), ('rejected', 'Rejetée')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teacher_payment_claims',
            },
        ),
    ]
