# Generated by Django 5.1.6 on 2025-11-17 16:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_app", "0001_initial"),
        ("student_profile_app", "0003_alter_student_matricule"),
        ("teacher_app", "0003_alter_teacher_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exam_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("room", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_app.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        related_name="supervised_exams", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exam_sessions",
            },
        ),
        migrations.CreateModel(
            name="GradeComplaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_grade", models.FloatField()),
                ("complaint_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumise"),
                            ("assigned", "Attribuée"),
                            ("in_review", "En Révision"),
                            ("resolved", "Résolue"),
                            ("rejected", "Rejetée"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("new_grade", models.FloatField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_app.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile_app.student",
                    ),
                ),
            ],
            options={
                "db_table": "grade_complaints",
            },
        ),
        migrations.CreateModel(
            name="JurySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_name", models.CharField(max_length=255)),
                ("session_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifié"),
                            ("in_progress", "En Cours"),
                            ("completed", "Terminé"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("minutes_document", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury_members",
                    models.ManyToManyField(
                        related_name="jury_sessions", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "jury_sessions",
            },
        ),
        migrations.CreateModel(
            name="JuryDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("admitted", "Admis"),
                            ("deferred", "Ajourné"),
                            ("repeat", "Redoublement"),
                            ("excluded", "Exclu"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile_app.student",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jury_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_academic_secretary_app.jurysession",
                    ),
                ),
            ],
            options={
                "db_table": "jury_decisions",
            },
        ),
        migrations.CreateModel(
            name="OfficialDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("transcript", "Relevé de Notes"),
                            ("certificate", "Certificat"),
                            ("minutes", "Procès-Verbal"),
                            ("circular", "Circulaire"),
                            ("service_note", "Note de Service"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_signature", "En Attente de Signature"),
                            ("signed", "Signé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "official_documents",
            },
        ),
        migrations.CreateModel(
            name="TeacherPaymentClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hours_taught", models.IntegerField()),
                ("hourly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Soumise"),
                            ("verified", "Vérifiée"),
                            ("approved", "Approuvée"),
                            ("signed", "Signée"),
                            ("sent_to_finance", "Envoyée aux Finances"),
                            ("rejected", "Rejetée"),
                        ],
                        default="submitted",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_app.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_app.teacher",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "teacher_payment_claims",
            },
        ),
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("late", "Retard"),
                            ("incident", "Incident"),
                        ],
                        max_length=20,
                    ),
                ),
                ("incident_notes", models.TextField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile_app.student",
                    ),
                ),
                (
                    "exam_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_academic_secretary_app.examsession",
                    ),
                ),
            ],
            options={
                "db_table": "exam_attendance_secretary",
                "unique_together": {("exam_session", "student")},
            },
        ),
    ]
