# Generated by Django 5.1.6 on 2025-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_secretary_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examsession",
            name="course",
        ),
        migrations.RemoveField(
            model_name="examsession",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="examsession",
            name="supervisors",
        ),
        migrations.DeleteModel(
            name="ExamAttendance",
        ),
        migrations.DeleteModel(
            name="ExamSession",
        ),
    ]
