# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0003_initial'),
        ('course_app', '0001_initial'),
        ('dashboard_academic_secretary_app', '0001_initial'),
        ('student_profile_app', '0001_initial'),
        ('teacher_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradecomplaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gradecomplaint',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AddField(
            model_name='gradecomplaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile_app.student'),
        ),
        migrations.AddField(
            model_name='jurydecision',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_profile_app.student'),
        ),
        migrations.AddField(
            model_name='jurydecision',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurysession',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_sessions', to='class_app.classgroup'),
        ),
        migrations.AddField(
            model_name='jurysession',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurysession',
            name='jury_members',
            field=models.ManyToManyField(related_name='jury_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jurydecision',
            name='jury_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard_academic_secretary_app.jurysession'),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialdocument',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherpaymentclaim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherpaymentclaim',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course'),
        ),
        migrations.AddField(
            model_name='teacherpaymentclaim',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_app.teacher'),
        ),
        migrations.AddField(
            model_name='teacherpaymentclaim',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
