# Generated by Django 5.2.8 on 2026-05-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_secretary_app", "0003_alter_jurydecision_decision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurydecision",
            name="jury_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jury_decisions",
                to="dashboard_academic_secretary_app.jurysession",
            ),
        ),
    ]
