# Generated by Django 5.2.8 on 2026-01-15 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_class_is_default_and_more'),
        ('dashboard_academic_secretary_app', '0003_jurysession_add_classgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurysession',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_sessions', to='class_app.classgroup'),
        ),
    ]
