# Generated by Django 5.2.8 on 2026-06-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_academic_secretary_app', '0007_make_validated_by_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurydecision',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
