# Generated by Django 5.2.8 on 2026-06-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_secretary_app", "0008_make_validated_at_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jurydecision",
            options={"ordering": ["-validated_at", "id"]},
        ),
    ]
