# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty_app", "0001_initial"),
        ("room_app", "0001_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supervisor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_supervisor_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("position", models.CharField(max_length=100, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="dean_profile",
                        to="faculty_app.faculty",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="room_profiles",
                        to="room_app.room",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rector_profile",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "profiles",
            },
        ),
    ]
