# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorization_app", "0001_initial"),
        ("faculty_app", "0001_initial"),
        ("room_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dean_profile",
                to="faculty_app.faculty",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="room_profiles",
                to="room_app.room",
            ),
        ),
    ]
