# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorization_app", "0002_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="rector_profile",
                to="university_app.university",
            ),
        ),
    ]
