# Generated by Django 5.1.6 on 2025-12-18 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization_app", "0004_initial"),
        ("faculty_app", "0002_initial"),
        ("university_app", "0004_alter_academicyear_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="dean_profile",
                to="faculty_app.faculty",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="rector_profile",
                to="university_app.university",
            ),
        ),
    ]
