# Generated by Django 5.1.6 on 2025-12-30 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authorization_app",
            "0005_alter_profile_end_date_alter_profile_faculty_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
