# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profession_name", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "professions",
            },
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("parent_name", models.CharField(max_length=60)),
                ("parent_phone", models.CharField(max_length=15)),
                (
                    "parent_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "parent_type",
                    models.CharField(
                        choices=[("F", "Father"), ("M", "Mother"), ("G", "Guardian")],
                        max_length=1,
                    ),
                ),
                ("is_alive", models.BooleanField(default=True)),
                ("is_contact_person", models.BooleanField(default=False)),
                (
                    "profession",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="parent_app.profession",
                    ),
                ),
            ],
            options={
                "db_table": "parents",
            },
        ),
    ]
