# Generated by Django 5.2.8 on 2026-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parent_app", "0002_alter_parent_parent_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="parent_type",
            field=models.CharField(
                choices=[
                    ("F", "Father"),
                    ("M", "Mother"),
                    ("G", "Guardian"),
                    ("T", "Tuteur"),
                ],
                max_length=1,
            ),
        ),
    ]
