# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "classes",
            },
        ),
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("group_name", models.CharField(max_length=50)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "class_groups",
            },
        ),
    ]
