# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0001_initial"),
        ("department_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="classes",
                to="department_app.department",
            ),
        ),
    ]
