# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0002_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="university_app.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="class_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="class_app.class",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("class_name", "department")},
        ),
        migrations.AlterUniqueTogether(
            name="classgroup",
            unique_together={("class_fk", "academic_year", "group_name")},
        ),
    ]
