# Generated by Django 5.2.8 on 2026-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_initial'),
        ('department_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('department',), name='one_default_class_per_department'),
        ),
    ]
