# Generated by Django 5.2.8 on 2026-01-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0004_class_is_default_and_more'),
        ('university_app', '0004_alter_academicyear_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='classgroup',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='classgroup',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('class_fk', 'academic_year'), name='one_default_group_per_class_year'),
        ),
    ]
