# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'semesters',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='modules', to='class_app.class')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='module_app.semester')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
