# Generated by Django 5.2.8 on 2025-12-01 14:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "semesters",
                "ordering": ["number"],
            },
        ),
        migrations.RemoveField(
            model_name="module",
            name="semester_id",
        ),
        migrations.AddField(
            model_name="module",
            name="semester",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="module_app.semester",
            ),
            preserve_default=False,
        ),
    ]
