# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("country_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=255)),
                ("civil_year", models.CharField(max_length=4)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
            options={
                "db_table": "academic_years",
            },
        ),
        migrations.CreateModel(
            name="UniversityDegree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("degree_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "university_degrees",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university_name", models.CharField(max_length=255)),
                (
                    "university_abrev",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="universities",
                        to="country_app.country",
                    ),
                ),
            ],
            options={
                "db_table": "universities",
            },
        ),
    ]
