# Generated by Django 5.2 on 2025-11-24 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=15)),
                ("description", models.CharField(max_length=255)),
                ("civil_year", models.CharField(max_length=4)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_closed", models.BooleanField(default=False)),
                ("closed_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "academic_years",
            },
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("university_name", models.CharField(max_length=255)),
                (
                    "university_abrev",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
            ],
            options={
                "db_table": "universities",
            },
        ),
        migrations.CreateModel(
            name="UniversityAdmin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_super_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UniversityDegree",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("degree_name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "university_degrees",
            },
        ),
    ]
