# Generated by Django 5.1.6 on 2025-11-17 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="closed_academic_years",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="closed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="academicyear",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
    ]
