# Generated by Django 5.2.8 on 2025-12-08 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_app", "0001_initial"),
        ("university_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="university",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="universities",
                to="country_app.country",
            ),
        ),
    ]
