# Generated by Django 5.1.6 on 2025-12-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("university_app", "0003_alter_university_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_years",
                to="university_app.university",
            ),
        ),
    ]
