# Generated by Django 5.2.8 on 2026-01-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university_app', '0004_alter_academicyear_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
