# Generated by Django 5.1.6 on 2025-11-17 16:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student_profile_app", "0003_alter_student_matricule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDerogation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "derogation_type",
                    models.CharField(
                        choices=[
                            ("exemption", "Exemption"),
                            ("postponement", "Report"),
                            ("arrangement", "Aménagement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("supporting_documents", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="requested_derogations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviewed_derogations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="student_profile_app.student",
                    ),
                ),
            ],
            options={
                "db_table": "payment_derogations",
            },
        ),
        migrations.CreateModel(
            name="RecteurDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("payment_derogation", "Dérogation de Paiement"),
                            ("course_attribution", "Attribution de Cours"),
                            (
                                "exceptional_authorization",
                                "Autorisation Exceptionnelle",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("reference_id", models.CharField(max_length=255)),
                ("decision", models.CharField(max_length=20)),
                ("notes", models.TextField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recteur_decisions",
            },
        ),
    ]
