# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard_academic_app", "0001_initial"),
        ("teacher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attributionvalidation",
            name="attribution",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="teacher_app.attribution",
            ),
        ),
    ]
