# Generated by Django 5.2.8 on 2025-11-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QualityReport",
        ),
    ]
