# Generated by Django 5.2.8 on 2026-01-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_app", "0004_delete_qualityreport"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AttributionValidation",
        ),
    ]
