# Generated by Django 5.2.8 on 2026-01-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_academic_app', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttributionValidation',
        ),
    ]
