# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=3, null=True)),
                ("country_name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "countries",
            },
        ),
    ]
