# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colline_name', models.CharField(max_length=45)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collines', to='zone_app.zone')),
            ],
            options={
                'db_table': 'collines',
            },
        ),
    ]
