# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees_app", "0001_initial"),
        ("inscription_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_abreviation", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "banks",
            },
        ),
        migrations.CreateModel(
            name="PaymentsHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("updated", "Updated"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=7,
                    ),
                ),
                ("action_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "payments_history",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.PositiveIntegerField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reception_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_deposit", "Bank Deposit"),
                            ("bank_transfert", "Bank Transfer"),
                            ("bank_check", "Bank Check"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_slip_ref", models.CharField(max_length=128, null=True)),
                ("transaction_code", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=250, null=True)),
                ("remittance_slip_uri", models.CharField(max_length=255, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
                (
                    "bank",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="bank",
                        to="payment_app.bank",
                    ),
                ),
                (
                    "feessheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments_frrssheet",
                        to="fees_app.feessheet",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments_inscription",
                        to="inscription_app.inscription",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
    ]
