# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_history",
                to="payment_app.payment",
            ),
        ),
        migrations.AddField(
            model_name="paymentshistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_history_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
