# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExamAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attendance_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("unauthorized", "Unauthorized"),
                            ("late", "Retard"),
                            ("incident", "Incident"),
                        ],
                        default="present",
                        max_length=12,
                    ),
                ),
                ("incident_notes", models.TextField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "exam_attendances",
            },
        ),
    ]
