# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance_app", "0001_initial"),
        ("card_app", "0001_initial"),
        ("exam_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattendance",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="card_app.studentcard",
            ),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="examroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="exam_app.examroom"
            ),
        ),
    ]
