# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance_app", "0002_initial"),
        ("exam_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattendance",
            name="examroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="exam_app.examroom"
            ),
        ),
    ]
