# Generated by Django 5.1.6 on 2025-11-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_app", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examattendance",
            name="incident_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="recorded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="examattendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("unauthorized", "Unauthorized"),
                    ("late", "Retard"),
                    ("incident", "Incident"),
                ],
                default="present",
                max_length=12,
            ),
        ),
    ]
