# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance_app", "0003_initial"),
        ("inscription_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattendance",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="inscription_app.inscription",
            ),
        ),
    ]
