# Generated by Django 5.2.8 on 2025-12-05 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_shared_app", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuprecord",
            name="initiated_by",
        ),
        migrations.AlterUniqueTogether(
            name="systemconfiguration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="BackupRecord",
        ),
        migrations.DeleteModel(
            name="SystemConfiguration",
        ),
    ]
