# Generated by Django 5.1.6 on 2025-11-17 16:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_app", "0001_initial"),
        ("student_profile_app", "0003_alter_student_matricule"),
        ("teacher_app", "0003_alter_teacher_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "standard_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Standard"),
                            ("administrative", "Administrative Standard"),
                            ("accreditation", "Accreditation Requirement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("compliance_criteria", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quality_standards",
            },
        ),
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_period", models.CharField(max_length=100)),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partially_compliant", "Partially Compliant"),
                            ("under_review", "Under Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
                (
                    "audited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_quality_director_app.qualitystandard",
                    ),
                ),
            ],
            options={
                "db_table": "compliance_audits",
            },
        ),
        migrations.CreateModel(
            name="StudentSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "survey_type",
                    models.CharField(
                        choices=[
                            ("course_evaluation", "Course Evaluation"),
                            ("teacher_evaluation", "Teacher Evaluation"),
                            ("environment_satisfaction", "Environment Satisfaction"),
                        ],
                        max_length=50,
                    ),
                ),
                ("responses", models.JSONField(default=dict)),
                ("rating", models.IntegerField()),
                ("comments", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course_app.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_profile_app.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_app.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "student_surveys",
            },
        ),
    ]
