# Generated by Django 5.2 on 2025-11-24 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_period", models.CharField(max_length=100)),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partially_compliant", "Partially Compliant"),
                            ("under_review", "Under Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_audits",
            },
        ),
        migrations.CreateModel(
            name="QualityStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("compliance_criteria", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quality_standards",
            },
        ),
    ]
