# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicPerformanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "semester",
                    models.IntegerField(choices=[(1, "Semester 1"), (2, "Semester 2")]),
                ),
                ("success_rate", models.FloatField()),
                ("failure_rate", models.FloatField()),
                ("average_grade", models.FloatField()),
                ("underperforming_courses", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "academic_performance_reports",
            },
        ),
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("audit_period", models.CharField(max_length=100)),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("partially_compliant", "Partially Compliant"),
                            ("under_review", "Under Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("findings", models.JSONField(default=dict)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("audit_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_audits",
            },
        ),
        migrations.CreateModel(
            name="CourseSatisfactionSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("teacher_name", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "course_quality_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "teacher_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "environment_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("survey_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "course_satisfaction_surveys",
            },
        ),
        migrations.CreateModel(
            name="ProgramExecutionTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=9)),
                ("planned_coverage", models.IntegerField()),
                ("actual_coverage", models.IntegerField()),
                ("progress_percentage", models.FloatField()),
                ("objectives_met", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "program_execution_tracking",
            },
        ),
        migrations.CreateModel(
            name="QualityStandard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("compliance_criteria", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quality_standards",
            },
        ),
        migrations.CreateModel(
            name="StudentRetentionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                ("total_enrolled", models.IntegerField()),
                ("retained_students", models.IntegerField()),
                ("retention_rate", models.FloatField()),
                ("dropout_rate", models.FloatField()),
                ("dropout_reasons", models.JSONField(default=dict)),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_retention_audits",
            },
        ),
    ]
