# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard_quality_director_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="academicperformancereport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceaudit",
            name="audited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="programexecutiontracking",
            unique_together={("program_name", "academic_year")},
        ),
        migrations.AddField(
            model_name="qualitystandard",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceaudit",
            name="standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_quality_director_app.qualitystandard",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentretentionaudit",
            unique_together={("academic_year",)},
        ),
        migrations.AlterUniqueTogether(
            name="academicperformancereport",
            unique_together={("academic_year", "semester")},
        ),
    ]
