# Generated by Django 5.2.8 on 2025-11-26 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_quality_director_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseSatisfactionSurvey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("course_name", models.CharField(max_length=255)),
                ("teacher_name", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "course_quality_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "teacher_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                (
                    "environment_rating",
                    models.IntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("survey_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "course_satisfaction_surveys",
            },
        ),
        migrations.CreateModel(
            name="ProgramExecutionTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=9)),
                ("planned_coverage", models.IntegerField()),
                ("actual_coverage", models.IntegerField()),
                ("progress_percentage", models.FloatField()),
                ("objectives_met", models.BooleanField(default=False)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "program_execution_tracking",
                "unique_together": {("program_name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="StudentRetentionAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                ("total_enrolled", models.IntegerField()),
                ("retained_students", models.IntegerField()),
                ("retention_rate", models.FloatField()),
                ("dropout_rate", models.FloatField()),
                ("dropout_reasons", models.JSONField(default=dict)),
                ("audited_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_retention_audits",
                "unique_together": {("academic_year",)},
            },
        ),
        migrations.CreateModel(
            name="AcademicPerformanceReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(max_length=9)),
                (
                    "semester",
                    models.IntegerField(choices=[(1, "Semester 1"), (2, "Semester 2")]),
                ),
                ("success_rate", models.FloatField()),
                ("failure_rate", models.FloatField()),
                ("average_grade", models.FloatField()),
                ("underperforming_courses", models.JSONField(default=list)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "academic_performance_reports",
                "unique_together": {("academic_year", "semester")},
            },
        ),
    ]
