# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fees_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebtCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cancelation_date", models.DateField()),
                ("cancelled_amount", models.PositiveIntegerField()),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "feessheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payments_debt",
                        to="fees_app.feessheet",
                    ),
                ),
            ],
            options={
                "db_table": "debt_cancellations",
            },
        ),
    ]
