# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("concellation_app", "0001_initial"),
        ("inscription_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="debtcancellation",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="inscription_app.inscription",
            ),
        ),
    ]
