# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colline_app', '0001_initial'),
        ('parent_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('highschool_diploma', 'Highschool Diploma'), ('transcript', 'Transcript/Report Card'), ('id_copy', 'Copy of ID/Passport'), ('medical_certificate', 'Medical Certificate'), ('photo', 'Passport Photo'), ('parent_id_copy', 'Parent ID Copy'), ('other', 'Other Document')], max_length=30)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='student_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'student_files',
            },
        ),
        migrations.CreateModel(
            name='StudentGraduateInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, max_length=127, null=True)),
                ('mention', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'student_graduate_info',
            },
        ),
        migrations.CreateModel(
            name='StudentHsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('se_mark', models.CharField(blank=True, max_length=6, null=True)),
                ('date_of_obtention', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'student_hs_info',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domaine', models.CharField(max_length=255)),
                ('certificate', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'trainings',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('cam', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('colline', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='birthplaces', to='colline_app.colline')),
                ('parent', models.ManyToManyField(related_name='students_parents', to='parent_app.parent')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
