# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colline_app", "0001_initial"),
        ("parent_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGraduateInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=127, null=True)),
                ("mention", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "student_graduate_info",
            },
        ),
        migrations.CreateModel(
            name="StudentHsInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("se_mark", models.CharField(blank=True, max_length=6, null=True)),
                ("date_of_obtention", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "student_hs_info",
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("domaine", models.CharField(max_length=255)),
                ("certificate", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "trainings",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("matricule", models.CharField(max_length=12, unique=True)),
                ("cam", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "colline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="birthplaces",
                        to="colline_app.colline",
                    ),
                ),
                (
                    "parent",
                    models.ManyToManyField(
                        related_name="students_parents", to="parent_app.parent"
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
