# Generated by Django 5.1.6 on 2025-12-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_profile_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="studentfile",
            name="unique_student_file_type",
        ),
        migrations.AlterUniqueTogether(
            name="studentfile",
            unique_together={("student", "file_type")},
        ),
    ]
