# Generated by Django 5.2.8 on 2025-12-08 13:04

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colline_app", "0001_initial"),
        ("department_app", "0002_initial"),
        ("highschool_info_app", "0001_initial"),
        ("parent_app", "0001_initial"),
        ("student_profile_app", "0001_initial"),
        ("university_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGraduateInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("option", models.CharField(blank=True, max_length=127, null=True)),
                ("mention", models.CharField(max_length=45)),
            ],
            options={
                "db_table": "student_graduate_info",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="colline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="birthplaces",
                to="colline_app.colline",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent",
            field=models.ManyToManyField(
                related_name="students_parents", to="parent_app.parent"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="students_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentgraduateinfo",
            name="degree",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="university_app.universitydegree",
            ),
        ),
        migrations.AddField(
            model_name="studentgraduateinfo",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="department_app.department",
            ),
        ),
        migrations.AddField(
            model_name="studentgraduateinfo",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="graduate_infos",
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="studenthsinfo",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="highschool_info_app.certificate",
            ),
        ),
        migrations.AddField(
            model_name="studenthsinfo",
            name="highschool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="highschool_info_app.highschool",
            ),
        ),
        migrations.AddField(
            model_name="studenthsinfo",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="hs_infos",
                to="student_profile_app.student",
            ),
        ),

    ]
