# Generated by Django 5.1.6 on 2025-11-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_profile_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="matricule",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
