# Generated by Django 5.2.8 on 2025-12-05 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_profile_app", "0002_initial"),
        (
            "student_profile_app",
            "0002_student_studentgraduateinfo_studenthsinfo_training_and_more",
        ),
    ]

    operations = []
