# Generated by Django 5.2.8 on 2025-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_profile_app", "0003_alter_student_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="matricule",
            field=models.CharField(max_length=120, null=True, unique=True),
        ),
    ]
