# Generated by Django 5.1.6 on 2025-11-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_profile_app", "0004_alter_student_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="matricule",
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
