# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commune_app", "0001_initial"),
        ("zone_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "sections",
            },
        ),
        migrations.CreateModel(
            name="Highschool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hs_name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="highschools",
                        to="zone_app.zone",
                    ),
                ),
            ],
            options={
                "db_table": "highschools",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("option_name", models.CharField(max_length=45)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="options",
                        to="highschool_info_app.section",
                    ),
                ),
            ],
            options={
                "db_table": "options",
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("certificate_name", models.CharField(max_length=255)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certificates",
                        to="highschool_info_app.section",
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
            },
        ),
        migrations.CreateModel(
            name="TrainingCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="training_centers",
                        to="commune_app.commune",
                    ),
                ),
            ],
            options={
                "db_table": "training_centers",
            },
        ),
    ]
