# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0001_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wording_name", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "wordings",
            },
        ),
        migrations.CreateModel(
            name="FeesSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_amount", models.PositiveIntegerField()),
                ("installements", models.JSONField(default=list, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees_sheets_academicyear",
                        to="university_app.academicyear",
                    ),
                ),
                (
                    "class_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fees_sheets_class",
                        to="class_app.class",
                    ),
                ),
                (
                    "wording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="fees_sheets_wording",
                        to="fees_app.wording",
                    ),
                ),
            ],
            options={
                "db_table": "fees_sheets",
            },
        ),
    ]
