# Generated by Django 5.2.8 on 2026-01-29 12:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_user_created_at_user_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('identity', 'Identity Document'), ('photo', 'Profile Photo'), ('diploma', 'Diploma'), ('transcript', 'Transcript'), ('cv', 'CV'), ('cover_letter', 'Cover Letter'), ('teaching_cert', 'Teaching Certificate'), ('work_contract', 'Work Contract'), ('recommendation', 'Recommendation Letter'), ('research_proposal', 'Research Proposal'), ('admin_appointment', 'Admin Appointment Letter'), ('other', 'Other')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('file', models.FileField(upload_to='guest_documents/')),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guest_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_documents',
            },
        ),
        migrations.CreateModel(
            name='GuestRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_submitted', models.BooleanField(default=False)),
                ('profile_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user_app.role')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_guests', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guest_requests',
            },
        ),
        migrations.CreateModel(
            name='GuestNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('action_required', 'Action Required')], default='info', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guest_app.guestdocument')),
                ('guest_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='guest_app.guestrequest')),
            ],
            options={
                'db_table': 'guest_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guestdocument',
            name='guest_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='guest_app.guestrequest'),
        ),
        migrations.CreateModel(
            name='RoleDocumentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity', 'Identity Document'), ('photo', 'Profile Photo'), ('diploma', 'Diploma'), ('transcript', 'Transcript'), ('cv', 'CV'), ('cover_letter', 'Cover Letter'), ('teaching_cert', 'Teaching Certificate'), ('work_contract', 'Work Contract'), ('recommendation', 'Recommendation Letter'), ('research_proposal', 'Research Proposal'), ('admin_appointment', 'Admin Appointment Letter'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('max_size_mb', models.IntegerField(default=5)),
                ('accepted_formats', models.JSONField(default=list)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='user_app.role')),
            ],
            options={
                'db_table': 'role_document_requirements',
                'unique_together': {('role', 'document_type')},
            },
        ),
    ]
