# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GuestDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Document"),
                            ("photo", "Profile Photo"),
                            ("diploma", "Diploma"),
                            ("transcript", "Transcript"),
                            ("cv", "CV"),
                            ("cover_letter", "Cover Letter"),
                            ("teaching_cert", "Teaching Certificate"),
                            ("work_contract", "Work Contract"),
                            ("recommendation", "Recommendation Letter"),
                            ("research_proposal", "Research Proposal"),
                            ("admin_appointment", "Admin Appointment Letter"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="guest_documents/")),
                ("file_size", models.IntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "guest_documents",
            },
        ),
        migrations.CreateModel(
            name="GuestNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("action_required", "Action Required"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "guest_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("profile_submitted", models.BooleanField(default=False)),
                ("profile_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "guest_requests",
            },
        ),
        migrations.CreateModel(
            name="RoleDocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("identity", "Identity Document"),
                            ("photo", "Profile Photo"),
                            ("diploma", "Diploma"),
                            ("transcript", "Transcript"),
                            ("cv", "CV"),
                            ("cover_letter", "Cover Letter"),
                            ("teaching_cert", "Teaching Certificate"),
                            ("work_contract", "Work Contract"),
                            ("recommendation", "Recommendation Letter"),
                            ("research_proposal", "Research Proposal"),
                            ("admin_appointment", "Admin Appointment Letter"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("required", models.BooleanField(default=True)),
                ("max_size_mb", models.IntegerField(default=5)),
                ("accepted_formats", models.JSONField(default=list)),
            ],
            options={
                "db_table": "role_document_requirements",
            },
        ),
    ]
