# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("suggestion_date", models.DateField()),
                ("suggestion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "suggestions",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("teacher_grade", models.CharField(max_length=200)),
                ("speciality", models.CharField(blank=True, max_length=255, null=True)),
                ("url_cv", models.URLField(blank=True, null=True)),
                ("url_other", models.JSONField(blank=True, default=list, null=True)),
                (
                    "url_diploma",
                    models.FileField(
                        blank=True, null=True, upload_to="Teacher_diploma"
                    ),
                ),
            ],
            options={
                "db_table": "teachers",
            },
        ),
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_attribution", models.DateField()),
                (
                    "status_principal_teacher",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "status_substitute_teacher",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Refused", "Refused"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="university_app.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "attributions",
            },
        ),
    ]
