# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teacher_app", "0001_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribution",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="university_app.academicyear",
            ),
        ),
    ]
