# Generated by Django 5.2.8 on 2026-01-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_app", "0004_attribution_validated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribution",
            name="date_attribution",
            field=models.DateField(blank=True, null=True),
        ),
    ]
