# Generated by Django 5.2.8 on 2026-01-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_app", "0005_alter_attribution_date_attribution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribution",
            name="validation_status",
        ),
    ]

