# Generated by Django 5.2.8 on 2026-01-13 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher_app", "0006_remove_validation_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribution",
            name="principal_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="principal_attributions",
                to="teacher_app.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="attribution",
            name="status_principal_teacher",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="attribution",
            name="status_substitute_teacher",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Refused", "Refused"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="attribution",
            name="substitute_teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="substitute_attributions",
                to="teacher_app.teacher",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="teacher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
