# Generated by Django 5.2 on 2025-11-24 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=125, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField()),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")], max_length=6
                    ),
                ),
            ],
            options={
                "db_table": "external_notifications",
            },
        ),
    ]
