# Generated by Django 5.1.6 on 2025-11-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_notification_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="notification",
            table="external_notifications",
        ),
    ]
