# Generated by Django 5.2.8 on 2026-02-04 18:07

import uuid

import django.db.models.deletion
from django.db import migrations, models

import services.core_service.academic_module.public_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty_app", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("presentation", models.TextField()),
                ("content", models.JSONField(default=list)),
                ("admission_conditions", models.JSONField(default=list)),
                ("prerequisites", models.JSONField(default=list)),
                ("internship", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(max_length=50)),
                ("career_opportunities", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="faculty_app.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "programs",
            },
        ),
        migrations.CreateModel(
            name="ProgramImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=services.core_service.academic_module.public_app.models.program_image_upload_path
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "is_cover",
                    models.BooleanField(
                        default=False, help_text="Image principale du programme"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="public_app.program",
                    ),
                ),
            ],
            options={
                "db_table": "program_images",
            },
        ),
    ]
