# Generated by Django 5.2.8 on 2026-02-03 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty_app", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("presentation", models.TextField()),
                ("content", models.JSONField(default=list)),
                ("admission_conditions", models.JSONField(default=list)),
                ("prerequisites", models.JSONField(default=list)),
                ("internship", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(max_length=50)),
                ("career_opportunities", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="faculty_app.faculty",
                    ),
                ),
            ],
            options={
                "db_table": "programs",
            },
        ),
    ]
