# Generated by Django 5.2.8 on 2026-02-03 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="name",
        ),
    ]
