# Generated by Django 5.2.8 on 2026-02-03 16:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_app", "0002_remove_program_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
