"""
Django settings for UMS project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()


def get_env_variable(var_name, default=None):
    """Get environment variable or raise exception if not found and no default."""
    value = os.getenv(var_name, default)
    if value is None:
        raise Exception(f"Set the {var_name} environment variable")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret

SECRET_KEY = get_env_variable(
    "DJANGO_SECRET_KEY", "django-insecure-dev-key-change-in-production"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    "unfold.contrib.location_field",  # optional, if django-location-field package is used
    "unfold.contrib.constance",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "services.foundational_service.geo_module.country_app",
    "services.foundational_service.geo_module.province_app",
    "services.foundational_service.geo_module.commune_app",
    "services.foundational_service.geo_module.zone_app",
    "services.foundational_service.geo_module.colline_app",
    "services.foundational_service.auth_module.authorization_app",
    "services.foundational_service.auth_module.user_app",
    "services.foundational_service.auth_module.authentication_app",
    "services.core_service.academic_module.class_app",
    "services.core_service.academic_module.course_app",
    "services.core_service.academic_module.department_app",
    "services.core_service.academic_module.faculty_app",
    "services.core_service.academic_module.module_app",
    "services.core_service.academic_module.teacher_app",
    "services.core_service.academic_module.university_app",
    "services.core_service.finance_module.concellation_app",
    "services.core_service.finance_module.fees_app",
    "services.core_service.finance_module.payment_app",
    "services.core_service.student_module.card_app",
    "services.core_service.student_module.highschool_info_app",
    "services.core_service.student_module.inscription_app",
    "services.core_service.student_module.parent_app",
    "services.core_service.student_module.student_profile_app",
    "services.dependent_service.document_module.document_app",
    "services.dependent_service.document_module.request_app",
    "services.dependent_service.exam_module.attendance_app",
    "services.dependent_service.exam_module.exam_app",
    "services.dependent_service.exam_module.result_app",
    "services.dependent_service.infrastructure_module.building_app",
    "services.dependent_service.infrastructure_module.equipment_app",
    "services.dependent_service.infrastructure_module.room_app",
    "services.dependent_service.notification_module.event_notification_app",
    "services.dependent_service.scheduling_module.scheduling_app",
    "django_otp",
    "django_otp.plugins.otp_static",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_email",
    "django_extensions",
    "rest_framework",
    "corsheaders",
    "import_export",
    "simple_history",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_otp.middleware.OTPMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = "ums.urls"
AUTH_USER_MODEL = "user_app.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}
SPECTACULAR_SETTINGS = {
    "TITLE": "UMS API",
    "DESCRIPTION": "University Management System API Documentation",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Optional: customize tags, security, etc.
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "ums.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
