# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("province_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("commune_name", models.CharField(max_length=45)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="communes",
                        to="province_app.province",
                    ),
                ),
            ],
            options={
                "db_table": "communes",
            },
        ),
    ]
