# Generated by Django 5.2 on 2025-11-24 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("equipment_name", models.CharField(max_length=100)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("equipment_number", models.CharField(max_length=9)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("available", "Available"),
                            ("under_maintenance", "Under Maintenance"),
                            ("out_of_order", "Out of Order"),
                            ("disposed", "Disposed"),
                        ],
                        default="available",
                        max_length=86,
                    ),
                ),
            ],
            options={
                "db_table": "equipments",
            },
        ),
        migrations.CreateModel(
            name="EquipmentAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allocation_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("returned", "Returned"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        max_length=120,
                    ),
                ),
            ],
            options={
                "db_table": "equipment_allocations",
            },
        ),
        migrations.CreateModel(
            name="EquipmentMaintenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
            options={
                "db_table": "equipment_maintenance",
            },
        ),
        migrations.CreateModel(
            name="EquipmentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=45)),
            ],
        ),
    ]
