# Generated by Django 5.2.8 on 2025-11-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("working", "Working"),
                    ("available", "Available"),
                    ("under_maintenance", "Under Maintenance"),
                    ("out_of_order", "Out of Order"),
                    ("disposed", "Disposed"),
                ],
                default="available",
                max_length=86,
            ),
        ),
    ]
