# Generated by Django 5.2 on 2025-11-24 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("department_name", models.CharField(max_length=255)),
                ("abreviation", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "departments",
            },
        ),
    ]
