# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=255)),
                ('abreviation', models.CharField(max_length=20)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
