# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department_app", "0001_initial"),
        ("faculty_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="departments",
                to="faculty_app.faculty",
            ),
        ),
    ]
