# Generated by Django 5.2.8 on 2026-01-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_initial'),
        ('faculty_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('faculty',), name='one_default_department_per_faculty'),
        ),
    ]
