from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

# Initialize the DefaultRouter for ViewSet routing
router = DefaultRouter()
# Register the UserViewSet with the 'users' prefix
router.register(
    r"users", views.UserViewSet, basename="users"
)  # Fixed from userViews to UserViewSet

# Define URL patterns for the application
urlpatterns = [
    # Endpoint for user registration
    path("register/", views.RegisterView.as_view(), name="register"),
    # Endpoint to send OTP to user's email
    path("send-email-otp/", views.SendEmailOTPView.as_view(), name="send-email-otp"),
    # Endpoint to verify email using OTP
    path(
        "verify-email/", views.EmailOTPVerificationView.as_view(), name="verify-email"
    ),
    # Endpoint to complete reset password using OTP
    path(
        "password/reset/verify/",
        views.ResetPasswordWithOTPView.as_view(),
        name="reste-password",
    ),
    # Endpoint for user login
    path("login/", views.LoginView.as_view(), name="login_user"),
    path("login/email/", views.Email2FALoginView.as_view(), name="email-2fa-login"),
    path("login/totp/", views.TOTP2FALoginView.as_view(), name="totp-2fa-login"),
    path("login/static/", views.Static2FALoginView.as_view(), name="static-2fa-login"),
    # Endpoint for two-factor authentication
    # Setup 2FA
    path("2fa/set/email/", views.SetEmail2FAView.as_view(), name="set-email-2fa"),
    path("2fa/set/totp/", views.SetTOTP2FAView.as_view(), name="set-totp-2fa"),
    path("2fa/set/static/", views.SetStatic2FAView.as_view(), name="set-static-2fa"),
    # Verify 2FA
    path(
        "2fa/verify/email/", views.VerifyEmail2FAView.as_view(), name="verify-email-2fa"
    ),
    path("2fa/verify/totp/", views.VerifyTOTP2FAView.as_view(), name="verify-totp-2fa"),
    path(
        "2fa/verify/static/",
        views.VerifyStatic2FAView.as_view(),
        name="verify-static-2fa",
    ),
    # Disable 2FA
    path(
        "2fa/disable/email/",
        views.DisableEmail2FAView.as_view(),
        name="disable-email-2fa",
    ),
    path(
        "2fa/disable/totp/", views.DisableTOTP2FAView.as_view(), name="disable-totp-2fa"
    ),
    path(
        "2fa/disable/static/",
        views.DisableStatic2FAView.as_view(),
        name="disable-static-2fa",
    ),
    # Endpoint to refresh JWT tokens
    path("token/refresh/", views.TokenRefreshView.as_view(), name="token_refresh"),
    # Endpoint to get available active roles
    path("available-roles/", views.AvailableRoleView.as_view(), name="available_roles"),
    # Include all routes generated by the router (for ViewSets)
    path("", include(router.urls)),
    path(
        "hr/",
        include("services.foundational_service.auth_module.authorization_app.urls"),
    ),
    path("guest/", include("services.foundational_service.auth_module.guest_app.urls")),
    path("logout/", views.LogoutAPIView.as_view(), name="logout"),
]
