# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('password_reset', 'Réinitialisation Mot de Passe'), ('role_change', 'Changement de Rôle'), ('permission_change', 'Changement de Permission'), ('config_change', 'Changement Configuration'), ('backup_initiated', 'Sauvegarde Initiée'), ('restore_initiated', 'Restauration Initiée'), ('security_breach', 'Violation Sécurité'), ('failed_login', 'Échec Connexion'), ('account_locked', 'Compte Verrouillé')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=20)),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backup_type', models.CharField(choices=[('full', 'Sauvegarde Complète'), ('incremental', 'Sauvegarde Incrémentale'), ('differential', 'Sauvegarde Différentielle')], default='full', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('running', 'En Cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('backup_location', models.CharField(blank=True, max_length=500, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyRecovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recovery_type', models.CharField(choices=[('password_reset', 'Réinitialisation Mot de Passe'), ('account_unlock', 'Déverrouillage Compte'), ('role_restoration', 'Restauration Rôle'), ('data_recovery', 'Récupération Données'), ('system_restore', 'Restauration Système')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'En Attente'), ('in_progress', 'En Cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('result', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'emergency_recoveries',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'modules_subscription',
            },
        ),
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('feature', 'Fonctionnalité'), ('security', 'Sécurité'), ('notification', 'Notification'), ('global', 'Global')], max_length=50)),
                ('key', models.CharField(max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('trial', 'Trial')], default='active', max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=1000)),
                ('max_storage_gb', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'university_profiles',
            },
        ),
        migrations.CreateModel(
            name='UniversitySubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_trial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'university_subscriptions',
            },
        ),
    ]
