# Generated by Django 5.1.6 on 2025-11-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_super_admin_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backuprecord",
            name="initiated_by",
        ),
        migrations.AlterUniqueTogether(
            name="systemconfiguration",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="systemconfiguration",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="BackupRecord",
        ),
        migrations.DeleteModel(
            name="SystemConfiguration",
        ),
    ]
