# Generated by Django 5.2.8 on 2026-07-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_super_admin_app", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="entity_id",
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
