# Generated by Django 5.2 on 2025-11-24 12:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlumiDonation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("scholarship", "Bourse d'Études"),
                            ("research", "Recherche"),
                            ("equipment", "Équipement"),
                            ("general", "Général"),
                        ],
                        max_length=20,
                    ),
                ),
                ("purpose", models.TextField()),
                ("transaction_id", models.CharField(max_length=100, unique=True)),
                ("donated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alumni_donations",
            },
        ),
        migrations.CreateModel(
            name="AlumniEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("conference", "Conférence"),
                            ("workshop", "Atelier"),
                            ("networking", "Réseautage"),
                            ("graduation", "Remise de Diplômes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("max_attendees", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alumni_events",
            },
        ),
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("current_position", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "sector",
                    models.CharField(
                        choices=[
                            ("tech", "Technologie"),
                            ("finance", "Finance"),
                            ("health", "Santé"),
                            ("education", "Éducation"),
                            ("consulting", "Conseil"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("linkedin_profile", models.URLField(blank=True, null=True)),
                ("is_mentor", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alumni_profiles",
            },
        ),
        migrations.CreateModel(
            name="AlumniTestimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alumni_testimonials",
            },
        ),
        migrations.CreateModel(
            name="JobOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("internship", "Stage"),
                            ("full_time", "CDI"),
                            ("part_time", "CDD"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alumni_job_offers",
            },
        ),
        migrations.CreateModel(
            name="MentorshipProgram",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expertise_area", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Terminé"),
                            ("paused", "En Pause"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mentorship_programs",
            },
        ),
        migrations.CreateModel(
            name="AlumniEventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dashboard_alumni_app.alumnievent",
                    ),
                ),
            ],
            options={
                "db_table": "alumni_event_registrations",
            },
        ),
    ]
