# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard_alumni_app", "0001_initial"),
        ("student_profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="alumnieventregistration",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_alumni_app.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="alumidonation",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_alumni_app.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="alumnitestimonial",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_alumni_app.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="alumni",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_alumni_app.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipprogram",
            name="mentee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="mentorshipprogram",
            name="mentor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard_alumni_app.alumniprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alumnieventregistration",
            unique_together={("event", "alumni")},
        ),
    ]
