# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_name", models.CharField(max_length=100)),
                ("capacity", models.PositiveIntegerField()),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("classroom", "Classroom"),
                            ("laboratory", "Laboratory"),
                            ("amphi", "Amphi"),
                            ("office", "Office"),
                            ("meeting", "Meeting"),
                        ],
                        default="classroom",
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rooms",
                        to="building_app.building",
                    ),
                ),
            ],
            options={
                "db_table": "rooms",
            },
        ),
    ]
