# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('room_code', models.CharField(blank=True, max_length=100, null=True)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('amphi', 'Amphi'), ('office', 'Office'), ('meeting', 'Meeting')], default='classroom', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='building_app.building')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
