# Generated by Django 5.1.6 on 2025-12-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
