# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("document_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_date", models.DateTimeField()),
                (
                    "request_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("collected", "Collected"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=12,
                    ),
                ),
                ("payment_verified", models.BooleanField(default=False)),
                ("admin_comment", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="document_app.document",
                    ),
                ),
            ],
            options={
                "db_table": "requests",
            },
        ),
    ]
