# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request_app', '0001_initial'),
        ('student_profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='student_profile_app.student'),
        ),
    ]
