# Generated by Django 5.2.8 on 2025-12-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0003_alter_payment_remittance_slip_uri"),
        ("request_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="document_payment",
                to="dashboard_collection_agent_app.payment",
            ),
        ),
    ]
