# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0002_initial"),
        ("scheduling_app", "0002_initial"),
        ("teacher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="attribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="teacher_app.attribution",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="class_app.classgroup",
            ),
        ),
    ]
