# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room_app", "0001_initial"),
        ("scheduling_app", "0002_initial"),
        ("teacher_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="attribution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="teacher_app.attribution",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="room_app.room"
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="slot",
            field=models.ManyToManyField(to="scheduling_app.scheduleslot"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attendances",
                to="scheduling_app.timetable",
            ),
        ),
        migrations.AddField(
            model_name="activityreport",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="activity_reports",
                to="scheduling_app.timetable",
            ),
        ),
    ]
