# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room_app", "0001_initial"),
        ("scheduling_app", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="created_timetables",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="room_app.room"
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="slots",
            field=models.ManyToManyField(to="scheduling_app.scheduleslot"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="attendances",
                to="scheduling_app.timetable",
            ),
        ),
        migrations.AddField(
            model_name="activityreport",
            name="timetable",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="activity_reports",
                to="scheduling_app.timetable",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("class_group", "room", "start_date", "end_date")},
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("timetable", "student")},
        ),
    ]
