# Generated by Django 5.2.8 on 2025-11-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0003_initial"),
        ("teacher_app", "0003_alter_teacher_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="attribution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="teacher_app.attribution",
            ),
        ),
    ]
