# Generated by Django 5.2.8 on 2026-01-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_classgroup_is_default_and_more'),
        ('scheduling_app', '0005_timetablemerge'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_timetables', to='class_app.classgroup'),
        ),
    ]
