# Generated by Django 5.1.6 on 2025-11-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colline_app", "0001_initial"),
        ("country_app", "0001_initial"),
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="nationals",
                to="country_app.country",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.ManyToManyField(
                null=True, related_name="residences", to="colline_app.colline"
            ),
        ),
    ]
