# Generated by Django 5.1.6 on 2025-11-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colline_app", "0001_initial"),
        ("user_app", "0002_alter_user_nationality_alter_user_residence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="residence",
            field=models.ManyToManyField(
                blank=True, related_name="residences", to="colline_app.colline"
            ),
        ),
    ]
