# Generated by Django 5.1.6 on 2025-11-19 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("country_app", "0001_initial"),
        ("user_app", "0003_alter_user_residence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="nationals",
                to="country_app.country",
            ),
        ),
    ]
