# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecretaryNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("is_resolved", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "secretary_notes",
            },
        ),
        migrations.CreateModel(
            name="TeacherWorkload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_hours", models.IntegerField(default=0)),
                (
                    "assigned_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_permanent", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "teacher_workload",
            },
        ),
        migrations.CreateModel(
            name="TeachingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "teaching_progress",
                "ordering": ["faculty", "attribution"],
            },
        ),
    ]
