# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard_doyen_app', '0001_initial'),
        ('faculty_app', '0002_initial'),
        ('teacher_app', '0002_initial'),
        ('university_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='secretarynote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretarynote',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_app.faculty'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teaching_academic_year', to='university_app.academicyear'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='faculty_app.faculty'),
        ),
        migrations.AddField(
            model_name='teacherworkload',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachingprogress',
            name='attribution',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_progress', to='teacher_app.attribution'),
        ),
        migrations.AddField(
            model_name='teachingprogress',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_progresses', to='faculty_app.faculty'),
        ),
        migrations.AddField(
            model_name='teachingprogress',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='submitted_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='teacherworkload',
            unique_together={('faculty', 'teacher', 'academic_year')},
        ),
    ]
