# Generated by Django 5.2.8 on 2026-07-26 17:15

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0004_class_level"),
        ("course_app", "0001_initial"),
        ("dashboard_doyen_app", "0002_initial"),
        ("module_app", "0001_initial"),
        ("public_app", "0001_initial"),
        ("university_app", "0003_unique_open_academic_year_per_university"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("expected_credits", models.PositiveSmallIntegerField(default=30)),
                (
                    "expected_vhp_hours",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_templates",
                        to="university_app.academicyear",
                    ),
                ),
                (
                    "class_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="curriculum_templates",
                        to="class_app.class",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_curriculum_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duplicated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="duplicates",
                        to="dashboard_doyen_app.curriculumtemplate",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="curriculum_templates",
                        to="public_app.program",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_curriculum_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_templates",
                        to="module_app.semester",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_templates",
                "ordering": [
                    "-academic_year__start_date",
                    "class_fk__level",
                    "semester__number",
                    "-version",
                ],
            },
        ),
        migrations.CreateModel(
            name="CurriculumTeachingUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("is_required", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_teaching_units",
                        to="module_app.module",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_units",
                        to="dashboard_doyen_app.curriculumtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_teaching_units",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CurriculumCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("tpe_hours", models.PositiveSmallIntegerField(default=0)),
                ("tge_hours", models.PositiveSmallIntegerField(default=0)),
                ("is_mandatory", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="curriculum_courses",
                        to="course_app.course",
                    ),
                ),
                (
                    "teaching_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curriculum_courses",
                        to="dashboard_doyen_app.curriculumteachingunit",
                    ),
                ),
            ],
            options={
                "db_table": "curriculum_courses",
                "ordering": ["position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teaching_unit", "course"),
                        name="unique_course_per_curriculum_teaching_unit",
                    ),
                    models.UniqueConstraint(
                        fields=("teaching_unit", "position"),
                        name="unique_course_position_per_teaching_unit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("coefficient__gt", 0)),
                        name="curriculum_course_coefficient_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="curriculumtemplate",
            constraint=models.UniqueConstraint(
                fields=("class_fk", "academic_year", "semester", "version"),
                name="unique_curriculum_template_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumtemplate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("class_fk", "academic_year", "semester"),
                name="unique_published_curriculum_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumteachingunit",
            constraint=models.UniqueConstraint(
                fields=("template", "module"),
                name="unique_module_per_curriculum_template",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumteachingunit",
            constraint=models.UniqueConstraint(
                fields=("template", "position"),
                name="unique_teaching_unit_position_per_template",
            ),
        ),
    ]
