# Generated by Django 5.2 on 2025-11-24 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_abreviation", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "banks",
            },
        ),
        migrations.CreateModel(
            name="CollectionCorrespondence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "correspondence_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("letter", "Courrier"),
                            ("phone", "Téléphone"),
                            ("meeting", "Rencontre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("response", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "collection_correspondence",
            },
        ),
        migrations.CreateModel(
            name="FeesSheet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("base_amount", models.PositiveIntegerField()),
                ("installements", models.JSONField(default=list, null=True)),
            ],
            options={
                "db_table": "fees_sheets",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount_paid", models.PositiveIntegerField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("reception_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("bank_deposit", "Bank Deposit"),
                            ("bank_transfert", "Bank Transfer"),
                            ("bank_check", "Bank Check"),
                            ("mobile_money", "Mobile Money"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("bank_slip_ref", models.CharField(max_length=128, null=True)),
                ("transaction_code", models.CharField(max_length=50, null=True)),
                ("description", models.CharField(max_length=250, null=True)),
                ("remittance_slip_uri", models.CharField(max_length=255, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("unverified", "Unverified"),
                            ("rejected", "Rejected"),
                        ],
                        default="unverified",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.CreateModel(
            name="PaymentInstallement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("paid", "Payé"),
                            ("overdue", "En Retard"),
                            ("deferred", "Reporté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("paid_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_installments",
            },
        ),
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("completed", "Terminé"),
                            ("defaulted", "En Défaut"),
                            ("cancelled", "Annulé"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_plans",
            },
        ),
        migrations.CreateModel(
            name="PaymentPromise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "promised_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("promised_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("kept", "Respecté"),
                            ("broken", "Non Respecté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_promises",
            },
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("reminder_7", "Rappel J+7"),
                            ("reminder_30", "Relance J+30"),
                            ("formal_notice_60", "Mise en Demeure J+60"),
                            ("final_notice", "Dernier Avis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sent", "Envoyé"),
                            ("delivered", "Livré"),
                            ("failed", "Échec"),
                            ("pending", "En Attente"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "payment_reminders",
            },
        ),
        migrations.CreateModel(
            name="Wording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wording_name", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "wordings",
            },
        ),
    ]
