# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0003_initial"),
        ("dashboard_collection_agent_app", "0001_initial"),
        ("inscription_app", "0002_initial"),
        ("student_profile_app", "0001_initial"),
        ("university_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="collectioncorrespondence",
            name="sent_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="collectioncorrespondence",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees_sheets_academicyear",
                to="university_app.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="class_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fees_sheets_class",
                to="class_app.class",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="bank",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="bank",
                to="dashboard_collection_agent_app.bank",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="inscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_inscription",
                to="inscription_app.inscription",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentplan",
            name="feessheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paymentplan_feessheet",
                to="dashboard_collection_agent_app.feessheet",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paymentplan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_paymentplan",
                to="dashboard_collection_agent_app.paymentplan",
            ),
        ),
        migrations.AddField(
            model_name="paymentpromise",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentpromise",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="sent_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="paymentreminder",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="wording",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fees_sheets_wording",
                to="dashboard_collection_agent_app.wording",
            ),
        ),
    ]
