# Generated by Django 5.2.8 on 2025-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="remittance_slip_uri",
            field=models.ImageField(blank=True, null=True, upload_to="payment_slips/"),
        ),
    ]
