# Generated by Django 5.2.8 on 2026-02-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="declared_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Montant initial déclaré/saisi (trace originale)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Montant effectivement alloué au plan (après redistribution)",
                max_digits=10,
            ),
        ),
    ]
