# Generated by Django 5.2.8 on 2026-02-15 08:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0003_payment_declared_amount_alter_payment_amount_paid",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentAllocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("original", "Montant original déclaré"),
                            ("allocation", "Affectation au plan cible"),
                            ("redistribution", "Redistribution vers plan précédent"),
                            ("surplus", "Surplus transféré vers plan suivant"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "allocated_to_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard_collection_agent_app.paymentplan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="dashboard_collection_agent_app.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_allocation_logs",
                "ordering": ["created_at"],
            },
        ),
    ]
