# Generated by Django 5.1.6 on 2025-12-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0003_alter_payment_remittance_slip_uri"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feessheet",
            name="installements",
        ),
    ]
