# Generated by Django 5.2.8 on 2026-02-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0004_paymentallocationlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="declared_amount",
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
