# Generated by Django 5.2.8 on 2025-12-16 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0003_initial"),
        ("dashboard_collection_agent_app", "0004_remove_feessheet_installements"),
        ("department_app", "0002_initial"),
        ("faculty_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feessheet",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fees_sheets_department",
                to="department_app.department",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fees_sheets_faculty",
                to="faculty_app.faculty",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("class", "Classe"),
                    ("department", "Département"),
                    ("faculty", "Faculté"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentinstallement",
            name="payment_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="installments",
                to="dashboard_collection_agent_app.paymentplan",
            ),
        ),
        migrations.AlterField(
            model_name="feessheet",
            name="class_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="fees_sheets_class",
                to="class_app.class",
            ),
        ),
    ]
