# Generated by Django 5.2.8 on 2026-02-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0005_remove_payment_declared_amount_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="PaymentAllocationLog",
        ),
    ]
