# Generated by Django 5.2.8 on 2025-12-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0005_feessheet_department_feessheet_faculty_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feessheet",
            name="level",
        ),
    ]
