# Generated by Django 5.2.8 on 2025-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0006_remove_feessheet_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentplan",
            name="monthly_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
