# Generated by Django 5.2.8 on 2026-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0007_bordereau_bordereauline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bordereau",
            name="numero",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
