# Generated by Django 5.2.8 on 2025-12-20 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0007_alter_paymentplan_monthly_amount"),
        ("inscription_app", "0005_inscription_inscription_student_5e8f34_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="verified_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="inscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="payments_inscription",
                to="inscription_app.inscription",
            ),
        ),
    ]
