# Generated by Django 5.2.8 on 2025-12-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0008_payment_verified_at_payment_verified_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Description du plan (ex: Première tranche, Deuxième tranche, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="bank_slip_ref",
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="description",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_code",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
