# Generated by Django 5.2.8 on 2026-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_collection_agent_app', '0008_payment_verified_at_payment_verified_by_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='payment',
        #     name='bank_slip_ref',
        # ),
        # migrations.AddField(
        #     model_name='bank',
        #     name='account_number',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], default='active', max_length=20),
        ),
        # migrations.AddField(
        #     model_name='paymentplan',
        #     name='description',
        #     field=models.CharField(blank=True, help_text='Description du plan (ex: Première tranche, Deuxième tranche, etc.)', max_length=100, null=True),
        # ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
