# Generated by Django 5.2.8 on 2026-07-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0008_alter_bordereau_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="feessheet",
            name="apply_to_all_classes",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="apply_to_all_departments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="apply_to_all_faculties",
            field=models.BooleanField(default=False),
        ),
    ]
