# Generated by Django 5.2.8 on 2026-07-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0004_class_level"),
        ("dashboard_collection_agent_app", "0009_add_feesheet_scope_fields"),
        ("department_app", "0002_initial"),
        ("faculty_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feessheet",
            name="excluded_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="feesheet_excluded_classes",
                to="class_app.class",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="excluded_departments",
            field=models.ManyToManyField(
                blank=True,
                related_name="feesheet_excluded_departments",
                to="department_app.department",
            ),
        ),
        migrations.AddField(
            model_name="feessheet",
            name="excluded_faculties",
            field=models.ManyToManyField(
                blank=True,
                related_name="feesheet_excluded_faculties",
                to="faculty_app.faculty",
            ),
        ),
    ]
