# Generated by Django 5.2.8 on 2026-01-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0009_alter_payment_amount_paid_and_more"),
        (
            "dashboard_collection_agent_app",
            "0009_paymentplan_description_alter_payment_amount_paid_and_more",
        ),
    ]

    operations = []
