# Generated by Django 5.2.8 on 2026-01-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0009_paymentplan_description_alter_payment_amount_paid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="bank_account",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
