# Generated by Django 5.2.8 on 2026-01-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0010_bank_bank_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bank",
            old_name="bank_account",
            new_name="account_number",
        ),
        migrations.AddField(
            model_name="bank",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("suspended", "Suspendu"),
                    ("closed", "Fermé"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
