# Generated by Django 5.2.8 on 2026-01-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_collection_agent_app", "0010_bank_bank_account"),
        ("dashboard_collection_agent_app", "0010_merge_20260107_1144"),
    ]

    operations = []
