# Generated by Django 5.2.8 on 2026-01-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_collection_agent_app', '0011_merge_0010_bank_bank_account_0010_merge_20260107_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='bank_account',
            new_name='account_number',
        ),
    ]
