# Generated by Django 5.2.8 on 2026-01-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0011_rename_bank_account_bank_account_number_bank_status",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="bank_slip_ref",
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
