# Generated by Django 5.2.8 on 2026-01-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard_collection_agent_app",
            "0009_remove_payment_bank_slip_ref_bank_account_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bank",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Actif"),
                    ("inactive", "Inactif"),
                    ("suspended", "Suspendu"),
                    ("closed", "Fermé"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
