# Generated by Django 5.2.8 on 2026-01-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_collection_agent_app', '0012_rename_bank_account_bank_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('suspended', 'Suspendu'), ('closed', 'Fermé')], default='active', max_length=20),
        ),
    ]
