# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("faculty_name", models.CharField(max_length=255)),
                (
                    "faculty_abreviation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "faculties",
            },
        ),
        migrations.CreateModel(
            name="TypeFormation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Code for the type: F, I, M, D",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "type_formations",
            },
        ),
    ]
