# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeFormation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=5)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("faculty_name", models.CharField(max_length=255)),
                (
                    "faculty_abreviation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="faculties",
                        to="university_app.university",
                    ),
                ),
                (
                    "types",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="typeformation",
                        to="faculty_app.typeformation",
                    ),
                ),
            ],
            options={
                "db_table": "faculties",
            },
        ),
    ]
