# Generated by Django 5.1.6 on 2025-11-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("faculty_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="typeformation",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Code for the type: F, I, M, D",
                max_length=2,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="typeformation",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="typeformation",
            table="type_formations",
        ),
    ]
