# Generated by Django 5.2 on 2025-11-24 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty_app", "0001_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="faculties",
                to="university_app.university",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="types",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="typeformation",
                to="faculty_app.typeformation",
            ),
        ),
    ]
