# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QualityReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("academic_performance", "Academic Performance"),
                            ("retention_rate", "Retention Rate"),
                            ("success_rate", "Success Rate"),
                            ("program_advancement", "Program Advancement"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("summary", models.TextField(blank=True, null=True)),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quality_reports",
            },
        ),
    ]
