# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
