# Generated by Django 5.2.8 on 2025-11-24 09:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("document_name", models.CharField(max_length=100)),
                ("document_description", models.TextField(blank=True, null=True)),
                ("document_price", models.PositiveIntegerField(default=0)),
                ("processing_time", models.PositiveIntegerField(default=5)),
            ],
            options={
                "db_table": "documents",
            },
        ),
    ]
