# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization_app', '0004_initial'),
        ('exam_app', '0002_initial'),
        ('room_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examroom',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='exam_app.exam'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='room_app.room'),
        ),
        migrations.AddField(
            model_name='examsupervisor',
            name='exam_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='supervisors', to='exam_app.examroom'),
        ),
        migrations.AddField(
            model_name='examsupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authorization_app.supervisor'),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='exam_app.examtype'),
        ),
        migrations.AlterUniqueTogether(
            name='examsupervisor',
            unique_together={('exam_room', 'supervisor')},
        ),
    ]
