# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("building_name", models.CharField(max_length=100)),
                (
                    "building_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="buildings",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "buildings",
            },
        ),
    ]
