# Generated by Django 5.2 on 2025-11-24 12:03

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("building_name", models.CharField(max_length=100)),
                (
                    "building_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "buildings",
            },
        ),
    ]
