# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('building_app', '0001_initial'),
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings', to='university_app.university'),
        ),
    ]
