# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_inscription', models.DateField()),
                ('regist_status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Withdrawn', 'Withdrawn'), ('Dropped', 'Dropped'), ('Pending', 'Pending'), ('Suspended', 'Suspended'), ('Canceled', 'Canceled'), ('Replaced', 'Replaced'), ('Complement', 'Complement')], default='Pending', max_length=15)),
                ('withdrawal_date', models.DateField(blank=True, null=True)),
                ('is_year_close', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inscriptions',
            },
        ),
    ]
