# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0003_initial'),
        ('inscription_app', '0001_initial'),
        ('student_profile_app', '0001_initial'),
        ('university_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to='university_app.academicyear'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='class_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to='class_app.class'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='class_app.classgroup'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inscriptions', to='student_profile_app.student'),
        ),
        migrations.AddIndex(
            model_name='inscription',
            index=models.Index(fields=['student', 'academic_year', 'class_fk'], name='inscription_student_5e8f34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('student', 'academic_year', 'class_fk')},
        ),
    ]
