# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inscription_app", "0001_initial"),
        ("student_profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscriptions",
                to="student_profile_app.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscription",
            unique_together={("student", "academic_year", "class_fk")},
        ),
    ]
