# Generated by Django 5.2.8 on 2025-11-24 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("class_app", "0003_initial"),
        ("inscription_app", "0001_initial"),
        ("student_profile_app", "0001_initial"),
        ("university_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscriptions",
                to="university_app.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="class_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscriptions",
                to="class_app.class",
            ),
        ),
        migrations.AddField(
            model_name="inscription",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscriptions",
                to="student_profile_app.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inscription",
            unique_together={("student", "academic_year", "class_fk")},
        ),
    ]
