# Generated by Django 5.2.8 on 2025-12-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0003_initial"),
        ("inscription_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="class_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inscriptions",
                to="class_app.class",
            ),
        ),
    ]
