# Generated by Django 5.2.8 on 2026-04-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription_app", "0003_inscription_created_by_inscription_modified_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscription",
            name="modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
