# Generated by Django 5.1.6 on 2025-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription_app", "0003_alter_inscription_class_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="regist_status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Withdrawn", "Withdrawn"),
                    ("Dropped", "Dropped"),
                    ("Pending", "Pending"),
                    ("Suspended", "Suspended"),
                    ("Canceled", "Canceled"),
                    ("Replaced", "Replaced"),
                    ("Complement", "Complement"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
