# Generated by Django 5.2.8 on 2025-12-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_app", "0003_initial"),
        ("inscription_app", "0004_alter_inscription_regist_status"),
        (
            "student_profile_app",
            "0002_remove_studentfile_unique_student_file_type_and_more",
        ),
        ("university_app", "0004_alter_academicyear_university"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inscription",
            index=models.Index(
                fields=["student", "academic_year", "class_fk"],
                name="inscription_student_5e8f34_idx",
            ),
        ),
    ]
