# Generated by Django 5.2.8 on 2026-05-26 22:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inscription_app", "0004_inscription_modified_at"),
        ("student_profile_app", "0004_remove_student_matricule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplementRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("requirements", models.TextField(blank=True, null=True)),
                (
                    "amount_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("annual_renewal", models.BooleanField(default=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("validated", "Validé"),
                            ("paid", "Payé"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complement_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complement_requirements",
                        to="inscription_app.inscription",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complement_requirements",
                        to="student_profile_app.student",
                    ),
                ),
            ],
            options={
                "db_table": "complement_requirements",
            },
        ),
    ]
