# Generated by Django 5.2.8 on 2026-01-15 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0005_classgroup_is_default_and_more'),
        ('inscription_app', '0005_inscription_inscription_student_5e8f34_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='class_app.classgroup'),
        ),
    ]
