# Generated by Django 5.2.8 on 2026-06-06 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_academic_secretary_app", "0009_add_jury_decision_fk"),
        ("dashboard_collection_agent_app", "0006_delete_paymentallocationlog"),
        ("inscription_app", "0005_complementrequirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="complementrequirement",
            name="course_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="complementrequirement",
            name="feesheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complement_requirements",
                to="dashboard_collection_agent_app.feessheet",
            ),
        ),
        migrations.AddField(
            model_name="complementrequirement",
            name="jury_decision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complement_requirements",
                to="dashboard_academic_secretary_app.jurydecision",
            ),
        ),
        migrations.AddField(
            model_name="complementrequirement",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
