# Generated by Django 5.2.8 on 2026-02-02 15:39

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UniversityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Settings"),
                            ("financial", "Financial Settings"),
                            ("enrollment", "Enrollment Settings"),
                            ("notification", "Notification Settings"),
                            ("security", "Security Settings"),
                            ("feature", "Feature Flags"),
                            ("general", "General Settings"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "university_configurations",
            },
        ),
        migrations.CreateModel(
            name="UniversityNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("alert", "Alert"),
                            ("warning", "Warning"),
                            ("info", "Information"),
                            ("success", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "university_notifications",
            },
        ),
        migrations.CreateModel(
            name="UniversityStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("total_faculties", models.IntegerField(default=0)),
                ("total_departments", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                ("active_enrollments", models.IntegerField(default=0)),
                (
                    "pending_payments",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("completed_exams", models.IntegerField(default=0)),
                ("pending_document_requests", models.IntegerField(default=0)),
                ("statistics_data", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "University statistics",
                "db_table": "university_statistics",
            },
        ),
    ]
