# Generated by Django 5.1.6 on 2025-11-24 10:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("university_admin", "University Administrator"),
                            ("department_admin", "Department Administrator"),
                            ("faculty_admin", "Faculty Administrator"),
                            ("system_admin", "System Administrator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "permissions",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object defining specific permissions for this role",
                    ),
                ),
                ("can_manage_universities", models.BooleanField(default=False)),
                ("can_manage_admins", models.BooleanField(default=False)),
                ("can_manage_configurations", models.BooleanField(default=False)),
                ("can_view_analytics", models.BooleanField(default=True)),
                ("can_manage_academic_years", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "admin_roles",
            },
        ),
        migrations.CreateModel(
            name="UniversityStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("total_faculties", models.IntegerField(default=0)),
                ("total_departments", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                ("active_enrollments", models.IntegerField(default=0)),
                (
                    "pending_payments",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("completed_exams", models.IntegerField(default=0)),
                ("pending_document_requests", models.IntegerField(default=0)),
                (
                    "statistics_data",
                    models.JSONField(
                        default=dict, help_text="Additional statistics in JSON format"
                    ),
                ),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "University statistics",
                "db_table": "university_statistics",
            },
        ),
        migrations.CreateModel(
            name="AdminActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("configure", "Configure"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        help_text="Type of entity affected (e.g., Student, Course)",
                        max_length=100,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                (
                    "changes",
                    models.JSONField(default=dict, help_text="Details of changes made"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "admin_activities",
                "indexes": [
                    models.Index(
                        fields=["admin", "timestamp"],
                        name="admin_activ_admin_i_d876f7_idx",
                    ),
                    models.Index(
                        fields=["university", "timestamp"],
                        name="admin_activ_univers_b3bcbc_idx",
                    ),
                    models.Index(
                        fields=["action"], name="admin_activ_action_5e8b87_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "is_super_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Can manage all universities and admins",
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("position", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "phone_extension",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_admin_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "universities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Universities this admin can manage",
                        related_name="admin_profiles",
                        to="university_app.university",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_profiles",
                        to="dashboard_admin_app.adminrole",
                    ),
                ),
            ],
            options={
                "db_table": "admin_profiles",
                "indexes": [
                    models.Index(
                        fields=["is_super_admin"], name="admin_profi_is_supe_9aea6c_idx"
                    ),
                    models.Index(
                        fields=["status"], name="admin_profi_status_23ac0c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UniversityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Settings"),
                            ("financial", "Financial Settings"),
                            ("enrollment", "Enrollment Settings"),
                            ("notification", "Notification Settings"),
                            ("security", "Security Settings"),
                            ("feature", "Feature Flags"),
                            ("general", "General Settings"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="modified_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "university_configurations",
                "indexes": [
                    models.Index(
                        fields=["university", "category"],
                        name="university__univers_95fc82_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="university__is_acti_d6fc9b_idx"
                    ),
                ],
                "unique_together": {("university", "category", "key")},
            },
        ),
        migrations.CreateModel(
            name="UniversityNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("alert", "Alert"),
                            ("warning", "Warning"),
                            ("info", "Information"),
                            ("success", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "university_notifications",
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="university__recipie_731fb1_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="university__priorit_f8f14c_idx"
                    ),
                ],
            },
        ),
    ]
