# Generated by Django 5.2.8 on 2025-12-05 14:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("university_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityStatistics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("total_teachers", models.IntegerField(default=0)),
                ("total_faculties", models.IntegerField(default=0)),
                ("total_departments", models.IntegerField(default=0)),
                ("total_courses", models.IntegerField(default=0)),
                ("active_enrollments", models.IntegerField(default=0)),
                (
                    "pending_payments",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("completed_exams", models.IntegerField(default=0)),
                ("pending_document_requests", models.IntegerField(default=0)),
                ("statistics_data", models.JSONField(default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statistics",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "University statistics",
                "db_table": "university_statistics",
            },
        ),
        migrations.CreateModel(
            name="UniversityConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Settings"),
                            ("financial", "Financial Settings"),
                            ("enrollment", "Enrollment Settings"),
                            ("notification", "Notification Settings"),
                            ("security", "Security Settings"),
                            ("feature", "Feature Flags"),
                            ("general", "General Settings"),
                        ],
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="created_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="modified_configurations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "university_configurations",
                "indexes": [
                    models.Index(
                        fields=["university", "category"],
                        name="university__univers_95fc82_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="university__is_acti_d6fc9b_idx"
                    ),
                ],
                "unique_together": {("university", "category", "key")},
            },
        ),
        migrations.CreateModel(
            name="UniversityNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("system", "System Notification"),
                            ("alert", "Alert"),
                            ("warning", "Warning"),
                            ("info", "Information"),
                            ("success", "Success"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("action_url", models.CharField(blank=True, max_length=500, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_notifications",
                        to="university_app.university",
                    ),
                ),
            ],
            options={
                "db_table": "university_notifications",
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="university__recipie_731fb1_idx",
                    ),
                    models.Index(
                        fields=["priority"], name="university__priorit_f8f14c_idx"
                    ),
                ],
            },
        ),
    ]
