# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard_admin_app", "0001_initial"),
        ("university_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="universityconfiguration",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="created_configurations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="universityconfiguration",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="modified_configurations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="universityconfiguration",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="university_app.university",
            ),
        ),
        migrations.AddField(
            model_name="universitynotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="universitynotification",
            name="university",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_notifications",
                to="university_app.university",
            ),
        ),
        migrations.AddField(
            model_name="universitystatistics",
            name="university",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="statistics",
                to="university_app.university",
            ),
        ),
        migrations.AddIndex(
            model_name="universityconfiguration",
            index=models.Index(
                fields=["university", "category"], name="university__univers_95fc82_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="universityconfiguration",
            index=models.Index(
                fields=["is_active"], name="university__is_acti_d6fc9b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="universityconfiguration",
            unique_together={("university", "category", "key")},
        ),
        migrations.AddIndex(
            model_name="universitynotification",
            index=models.Index(
                fields=["recipient", "is_read"], name="university__recipie_731fb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="universitynotification",
            index=models.Index(
                fields=["priority"], name="university__priorit_f8f14c_idx"
            ),
        ),
    ]
