# Generated by Django 5.2.8 on 2025-11-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard_admin_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofile",
            name="admin_role",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="universities",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="user",
        ),
        migrations.AlterField(
            model_name="universitystatistics",
            name="statistics_data",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="AdminActivity",
        ),
        migrations.DeleteModel(
            name="AdminRole",
        ),
        migrations.DeleteModel(
            name="AdminProfile",
        ),
    ]
