# Generated by Django 5.1.6 on 2025-11-09 14:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("card_number", models.CharField(max_length=30, unique=True)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("lost", "Lost"),
                            ("replaced", "Replaced"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("printed_by", models.CharField(blank=True, max_length=100, null=True)),
                ("photo_url", models.CharField(blank=True, max_length=255, null=True)),
                ("qrcode_data", models.TextField()),
            ],
            options={
                "db_table": "student_cards",
            },
        ),
        migrations.CreateModel(
            name="StudentCardLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("renewed", "Renewed"),
                            ("replaced", "Replaced"),
                            ("blocked", "Blocked"),
                            ("unblocked", "Unblocked"),
                        ],
                        max_length=9,
                    ),
                ),
                ("action_date", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "student_card_logs",
            },
        ),
    ]
