# Generated by Django 5.1.6 on 2025-11-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("card_app", "0001_initial"),
        ("student_profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="student_profile_app.student",
            ),
        ),
        migrations.AddField(
            model_name="studentcardlog",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="logs",
                to="card_app.studentcard",
            ),
        ),
    ]
