# Generated by Django 5.2.8 on 2026-02-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_app', '0001_initial'),
        ('student_profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcard',
            name='printed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentcard',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='student_profile_app.student'),
        ),
        migrations.AddField(
            model_name='studentcardlog',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='logs', to='card_app.studentcard'),
        ),
    ]
