# Generated by Django 5.1.6 on 2025-11-13 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_app", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcard",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="studentcard",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="student_cards/photos/"
            ),
        ),
        migrations.AlterField(
            model_name="studentcard",
            name="printed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="printed_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
