# Generated by Django 5.1.6 on 2025-11-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_app", "0003_remove_studentcard_photo_url_studentcard_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcard",
            name="card_number",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
