# Generated by Django 5.1.6 on 2025-11-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_app", "0004_alter_studentcard_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcard",
            name="qrcode_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
