# Generated by Django 5.2 on 2025-11-24 12:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AbsenceJustification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("medical", "Maladie"),
                            ("family_emergency", "Urgence Familiale"),
                            ("official_duty", "Devoir Officiel"),
                            ("other", "Autre"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                ("supporting_documents", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "absence_justifications",
            },
        ),
        migrations.CreateModel(
            name="CounselingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("orientation", "Orientation"),
                            ("academic_counseling", "Conseil Académique"),
                            ("methodological", "Méthodologique"),
                            ("career_guidance", "Orientation Professionnelle"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("location", models.CharField(max_length=255)),
                ("is_group_session", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "counseling_sessions",
            },
        ),
        migrations.CreateModel(
            name="DocumentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("diploma", "Diplôme"),
                            ("success_certificate", "Attestation de Réussite"),
                            ("attendance_certificate", "Attestation de Fréquentation"),
                            ("generic_certificate", "Attestation À qui de Droit"),
                        ],
                        max_length=50,
                    ),
                ),
                ("purpose", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("processing", "En Traitement"),
                            ("ready", "Prêt"),
                            ("delivered", "Livré"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "document_requests",
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("government", "Gouvernementale"),
                            ("private", "Privée"),
                            ("international", "Internationale"),
                            ("merit", "Mérite Académique"),
                        ],
                        max_length=50,
                    ),
                ),
                ("provider", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("academic_year", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "scholarships",
            },
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("club", "Club Étudiant"),
                            ("association", "Association"),
                            ("event", "Événement"),
                            ("conference", "Conférence"),
                            ("sports", "Activité Sportive"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "student_activities",
            },
        ),
        migrations.CreateModel(
            name="StudentStatusChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status_type",
                    models.CharField(
                        choices=[
                            ("withdrawal", "Abandon"),
                            ("exclusion", "Exclusion"),
                            ("suspension", "Suspension"),
                            ("cancellation", "Annulation Année Académique"),
                            ("transfer", "Transfert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField()),
                ("supporting_documents", models.JSONField(blank=True, default=list)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "En Attente"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "student_status_changes",
                "ordering": ["-requested_at"],
            },
        ),
    ]
